name: arc-flags
codename: mystique
image: ghcr.io/arc-framework/arc-flags:latest
tech: unleash
upstream: unleashorg/unleash-server
ports:
  - 4242
health: http://localhost:4242/health
depends_on:
  - oracle
  - sonic
