codename: friday
image: ghcr.io/arc-framework/arc-friday:latest
tech: arc-friday
depends_on:
  - friday-collector
health: http://localhost:3301/api/v1/health
compose_services:
  - signoz
  - clickhouse
  - zookeeper
